CREATE TABLE `FloatShield` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`arduino_online_id` INT(11) NOT NULL,
	`Experiment` VARCHAR(255) NULL DEFAULT 'IDDLE' COLLATE 'utf8mb4_unicode_ci',
	`START` VARCHAR(255) NULL DEFAULT 'STOP' COLLATE 'utf8mb4_unicode_ci',
	`TIMER` INT(11) NULL DEFAULT NULL,
	`Kp` DECIMAL(10,2) NULL DEFAULT NULL,
	`Ti` DECIMAL(10,2) NULL DEFAULT NULL,
	`Td` DECIMAL(10,2) NULL DEFAULT NULL,
	`r1` DECIMAL(10,2) NULL DEFAULT NULL,
	`r2` DECIMAL(10,2) NULL DEFAULT NULL,
	`r3` DECIMAL(10,2) NULL DEFAULT NULL,
	`r4` DECIMAL(10,2) NULL DEFAULT NULL,
	`r5` DECIMAL(10,2) NULL DEFAULT NULL,
	`r6` DECIMAL(10,2) NULL DEFAULT NULL,
	`T` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `arduino_online_id` (`arduino_online_id`) USING BTREE,
	CONSTRAINT `FloatShield_ibfk_1` FOREIGN KEY (`arduino_online_id`) REFERENCES `arduino_online` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=27
;
